### ISSUE TITLE
Presenter Mode seems to be broken on Firefox

### ISSUE THREAD

**Issue by SeanKilleen** [hiroppy/fusuma#514]
## Info

- Operating System: Windows 10
- Node Version: tried with 12.18, 14.16.1, and 15.14.0
- Browser Name and Version: Firefox v88
- Fusuma Version: v2.8.3

## Type

- [x] bug
- [ ] feature request

### How can we reproduce the behavior?

From an empty folder:

* `npm init`
* `npm install fusuma -D`
* `npx fusuma init`
* `npx fusuma start` (or `npx fusuma build` and `npx fusuma start-prod`)

Then:

* Open from Firefox
* Click the hamburger menu
* Click the monitor icon

### Expected Behavior

An additional window opens that shows my presentation in presenter view

### Actual Behavior

A blank window opens, and appears to show console errors.

> ![image](https://user-images.githubusercontent.com/2148318/116788227-7aeac080-aa76-11eb-9651-9f0954384e46.png)

**Comment by SeanKilleen** [comment]
As a note, I have only tried v2.8.3 so far -- will attempt to use other versions and see if I can find a regression.

**Comment by SeanKilleen** [comment]
Confirmed that this is not happening for me with 1.15.1 but does happen with 2.0.0 as well. Each time I recreated with `npm init`, `npm install -D fusuma@[version]`, `npx fusuma init`, and `npx fusuma start`.

**Comment by hiroppy** [comment]
sorry for the late reply. I'll check this issue on firefox soon.

**Comment by SeanKilleen** [comment]
No worries at all! Open source communication is asynchronous by default :)

**Comment by rjmunro** [comment]
It also seems broken for me in Chrome as well. Using the demo at https://hiroppy.github.io/fusuma/intro/, I get a blank white screen either on my second screen or on my chromecast device. On my second screen, I opened dev tools and got:

![image](https://user-images.githubusercontent.com/108641/118006478-32b78200-b343-11eb-9c70-806b42d09493.png)

**Comment by hiroppy** [comment]
oh, maybe I'd updated swiper and then it has occurred, let me check

**Comment by hiroppy** [comment]
Sorry for the late fixing, I've fixed this and released it as 2.8.4. Please check it when you have a chance

**Comment by rjmunro** [comment]
https://hiroppy.github.io/fusuma/intro/ is still not working for me, but it looks you didn't update that yet (the gh-pages branch hasn't been updated).
