### ISSUE TITLE
Failed to generate PDF

### ISSUE THREAD

**Issue by peaceiris** [hiroppy/fusuma#65]
- macOS 10.14.4
- fusuma 1.0.0
- Node v12.1.0
- npm 6.9.0

```sh
cd ./samples/intro
npm i fusuma -D
npx fusuma pdf
```

<details>
<summary>Click to expand (outputs)</summary>

```
⠇ Building with webpack...
 name                                                   size  

 c2c9fa6df062f6d39b0afa917f5e18b9.png                   128KB 

 vendors~Sidebar.0.3e4761d264be40e09343.css             2KB   

 vendors~Sidebar.0.3e4761d264be40e09343.bundle.js       23KB  

 main.1.a356ca4ff1254da5fd60.css                        1KB   

 main.1.a356ca4ff1254da5fd60.bundle.js                  11KB  

 presenter.view.2.1894e7277a414ac6e213.bundle.js        3KB   

 runtime.e0bc3d497d5c33c05f7d.bundle.js                 3KB   

 target-blank.4.e1582a590ae4c5c2ba46.bundle.js          350B  

 vendor.5.ddf6246fdd2f6b8bf90b.css                      50KB  

 vendor.5.ddf6246fdd2f6b8bf90b.bundle.js                295KB 

 index.html                                             1KB   

 precache-manifest.b7fdc1d629a679b913c9988d796566b2.js  780B  

 service-worker.js                                      1005B 


⠦ Exporting as PDFChildProcessError: `npm install decktape --no-save` failed with code 1
    at ChildProcess.<anonymous> (/Users/iris/Documents/repos/github.com/peaceiris/fusuma/samples/intro/node_modules/child-process-promise/lib/index.js:132:23)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1000:16)
    at Socket.<anonymous> (internal/child_process.js:405:11)
    at Socket.emit (events.js:196:13)
    at Pipe.<anonymous> (net.js:586:12) {
  name: 'ChildProcessError',
  code: 1,
  childProcess: ChildProcess {
    _events: [Object: null prototype] { error: [Function], close: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _closesNeeded: 3,
    _closesGot: 3,
    connected: false,
    signalCode: null,
    exitCode: 1,
    killed: false,
    spawnfile: 'npm',
    _handle: null,
    spawnargs: [ 'npm', 'install', 'decktape', '--no-save' ],
    pid: 66969,
    stdin: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: false,
      _events: [Object],
      _eventsCount: 1,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      [Symbol(asyncId)]: 48021,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    stdout: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: false,
      _events: [Object],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      write: [Function: writeAfterFIN],
      [Symbol(asyncId)]: 48022,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 12693,
      [Symbol(kBytesWritten)]: 0
    },
    stderr: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: false,
      _events: [Object],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      write: [Function: writeAfterFIN],
      [Symbol(asyncId)]: 48023,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 4503,
      [Symbol(kBytesWritten)]: 0
    },
    stdio: [ [Socket], [Socket], [Socket] ]
  },
  stdout: undefined,
  stderr: undefined
}
```

</details>

**Comment by hiroppy** [comment]
Thank you for reporting. I'll investigate it.

**Comment by hiroppy** [comment]
I have just published v1.0.1.

**Comment by peaceiris** [comment]
Thanks, but it still does not work.

<details>
<summary>Click to expand</summary>

```
⠴ Building with webpack...
 name                                                   size  

 c2c9fa6df062f6d39b0afa917f5e18b9.png                   128KB 

 vendors~Sidebar.0.3e4761d264be40e09343.css             2KB   

 vendors~Sidebar.0.3e4761d264be40e09343.bundle.js       23KB  

 main.1.9d40ba49d4b81b1ff0f0.css                        1KB   

 main.1.9d40ba49d4b81b1ff0f0.bundle.js                  11KB  

 presenter.view.2.1894e7277a414ac6e213.bundle.js        3KB   

 runtime.e0bc3d497d5c33c05f7d.bundle.js                 3KB   

 target-blank.4.e1582a590ae4c5c2ba46.bundle.js          350B  

 vendor.5.dec9da0c60001b78a178.css                      50KB  

 vendor.5.dec9da0c60001b78a178.bundle.js                295KB 

 index.html                                             1KB   

 precache-manifest.661082cb0a155685e81dba1cd9b69e2d.js  780B  

 service-worker.js                                      1005B 


ChildProcessError: `npm install decktape --no-save` failed with code 1
    at ChildProcess.<anonymous> (/Users/iris/Documents/repos/github.com/peaceiris/fusuma/samples/intro/node_modules/child-process-promise/lib/index.js:132:23)
    at ChildProcess.emit (events.js:196:13)
    at maybeClose (internal/child_process.js:1000:16)
    at Socket.<anonymous> (internal/child_process.js:405:11)
    at Socket.emit (events.js:196:13)
    at Pipe.<anonymous> (net.js:586:12) {
  name: 'ChildProcessError',
  code: 1,
  childProcess: ChildProcess {
    _events: [Object: null prototype] { error: [Function], close: [Function] },
    _eventsCount: 2,
    _maxListeners: undefined,
    _closesNeeded: 3,
    _closesGot: 3,
    connected: false,
    signalCode: null,
    exitCode: 1,
    killed: false,
    spawnfile: 'npm',
    _handle: null,
    spawnargs: [ 'npm', 'install', 'decktape', '--no-save' ],
    pid: 44913,
    stdin: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: false,
      _events: [Object],
      _eventsCount: 1,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      [Symbol(asyncId)]: 47937,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    stdout: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: false,
      _events: [Object],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      write: [Function: writeAfterFIN],
      [Symbol(asyncId)]: 47938,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 12693,
      [Symbol(kBytesWritten)]: 0
    },
    stderr: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: false,
      _events: [Object],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      write: [Function: writeAfterFIN],
      [Symbol(asyncId)]: 47939,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 4503,
      [Symbol(kBytesWritten)]: 0
    },
    stdio: [ [Socket], [Socket], [Socket] ]
  },
  stdout: undefined,
  stderr: undefined
}
```

</details>

**Comment by hiroppy** [comment]
fmmm, I cannot cause this issue. I checked [this repository](https://github.com/issue-verifier/fusuma).

**Comment by peaceiris** [comment]
```
npm i fusuma@v1.0.1 -D
npm run pdf
```

I got the same error.

**Comment by hiroppy** [comment]
what your npm and node.js version?

**Comment by peaceiris** [comment]
```
$ npm -v
6.9.0
$ node -v
v12.1.0
```

**Comment by peaceiris** [comment]
Now, I switched node v10.15.3 and run `npm run pdf`
It works well!

**Comment by hiroppy** [comment]
I changed these versions, and I could confirm this problem.

Yes, this is a problem with Node.js.(node-gyp)

```
../src/PDFStreamDriver.h:33:13: error: no template named 'Handle' in namespace 'v8'
        static v8::Handle<v8::Value> GetNewInstance(const ARGS_TYPE& args);
               ~~~~^
../src/PDFStreamDriver.h:34:33: error: no template named 'Handle' in namespace 'v8'
    static bool HasInstance(v8::Handle<v8::Value> inObject);
                            ~~~~^
In file included from ../src/PDFStreamDriver.cpp:22:
../src/ByteWriterDriver.h:33:13: error: no template named 'Handle' in namespace 'v8'
        static v8::Handle<v8::Value> GetNewInstance(const ARGS_TYPE& args);
               ~~~~^
../src/ByteWriterDriver.h:34:33: error: no template named 'Handle' in namespace 'v8'
    static bool HasInstance(v8::Handle<v8::Value> inObject);
                            ~~~~^
../src/PDFStreamDriver.cpp:47:18: warning: 'NewFromUtf8' is deprecated: Use maybe version [-Wdeprecated-declarations]
        t->SetClassName(NEW_STRING("PDFStream"));
                        ^
../src/nodes.h:18:31: note: expanded from macro 'NEW_STRING'
#define NEW_STRING(X) String::NewFromUtf8(isolate, X)
                              ^
/Users/about_hiroppy/.node-gyp/12.1.0/include/node/v8.h:2890:10: note: 'NewFromUtf8' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/about_hiroppy/.node-gyp/12.1.0/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/PDFStreamDriver.cpp:51:2: error: too few arguments to function call, single argument 'context' was not specified
        SET_CONSTRUCTOR(constructor,t);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/nodes.h:30:62: note: expanded from macro 'SET_CONSTRUCTOR'
#define SET_CONSTRUCTOR(c,t) c.Reset(isolate, t->GetFunction())
                                              ~~~~~~~~~~~~~~ ^
/Users/about_hiroppy/.node-gyp/12.1.0/include/node/v8.h:5947:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/about_hiroppy/.node-gyp/12.1.0/include/node/v8config.h:347:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/PDFStreamDriver.cpp:64:5: error: no template named 'Handle' in namespace 'v8'
v8::Handle<v8::Value> PDFStreamDriver::GetNewInstance(const ARGS_TYPE& args)
~~~~^
../src/PDFStreamDriver.cpp:70:9: error: no viable conversion from returned value of type 'Local<v8::Object>' to function return type 'int'
        return CLOSE_SCOPE(instance);
               ^~~~~~~~~~~~~~~~~~~~~
../src/nodes.h:41:24: note: expanded from macro 'CLOSE_SCOPE'
#define CLOSE_SCOPE(v) scope.Escape(v)
                       ^~~~~~~~~~~~~~~
../src/PDFStreamDriver.cpp:73:23: error: redefinition of 'HasInstance' as different kind of symbol
bool PDFStreamDriver::HasInstance(Handle<Value> inObject)
                      ^
../src/PDFStreamDriver.h:34:17: note: previous definition is here
    static bool HasInstance(v8::Handle<v8::Value> inObject);
                ^
../src/PDFStreamDriver.cpp:73:42: error: 'Value' does not refer to a value
bool PDFStreamDriver::HasInstance(Handle<Value> inObject)
                                         ^
/Users/about_hiroppy/.node-gyp/12.1.0/include/node/v8.h:2240:17: note: declared here
class V8_EXPORT Value : public Data {
                ^
../src/PDFStreamDriver.cpp:73:35: error: use of undeclared identifier 'Handle'
bool PDFStreamDriver::HasInstance(Handle<Value> inObject)
                                  ^
../src/PDFStreamDriver.cpp:73:49: error: use of undeclared identifier 'inObject'
bool PDFStreamDriver::HasInstance(Handle<Value> inObject)
                                                ^
../src/PDFStreamDriver.cpp:73:58: error: expected ';' after top level declarator
bool PDFStreamDriver::HasInstance(Handle<Value> inObject)
```

**Comment by hiroppy** [comment]
I open this pr until node-gyp problem will be resolved.

**Comment by harryleesan** [comment]
Still experiencing the same issue with node v14.5

PDF generation fails at "`npm install @fusuma/task-pdf --no-save` failed with code 1"

**Comment by hiroppy** [comment]
Thanks, this issue was fixed
